name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Run npm install
        run: npm install
      - name: create CA
        run: |
          node node_modules/node-opcua-pki/bin/crypto_create_CA.js demo
      - name: Install nexe
        run: |
          npm install -g nexe
      - name: Build weather.js for Linux
        run: |
          nexe weather.js -o weather
      - name: Build weather.js for Windows
        run: |
          nexe weather.js -t exe -o weather.exe
      - name: ls -lrt
        run: |
          ls -lrt
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "weather*"
          draft: "true"
          tag: "asdf"
          token: ${{ secrets.GITHUB_TOKEN }}
