name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install pkg if ubuntu
      run: |
          sudo npm install -g pkg
    - name: Run npm install      
      run: npm install
      env:
        CI: true
    - name: Build weather.js on ubuntu
      run: |
            pkg weather.js
    - name: ls -lrl
      run: |
            ls -lrt
    - name: try to run
      run: |
        echo "$APIKEY"
        timeout --preserve-status 120 ./weather-linux --apikey $APIKEY
      env:
        APIKEY: ${{ secrets.APIKEY }}