name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install pkg
      run: |
          sudo npm install -g pkg
    - name: Run npm install      
      run: npm install
    - name: create CA
      run: |
          node node_modules/node-opcua-pki/bin/crypto_create_CA.js demo
    - name: Build weather.js
      run: |
            pkg ${PWD}/weather.js
    - name: ls -lrl
      run: |
            ls -lrt
    - name: try to run
      run:  timeout --preserve-status 120 ./weather-linux --apikey ${{ secrets.APIKEY }}