name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install nexe
      run: |
           sudo npm install -g nexe
    - run: npm install
      env:
        CI: true
    - name: Build weather.js
      run: |
            nexe --build weather.js
            ls -lrt
