name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install nexe if ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo npm install -g nexe
    - name: Install nexe if windows
      if: matrix.os == 'windows-latest'
      run : |
          npm install -g nexe
    - name: Run npm install      
      run: npm install
      env:
        CI: true
    - name: Build weather.js on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
            nexe --build weather.js
    - name: Build weather.js on windows
      if: matrix.os == 'windows-latest'
      run: |
            nexe --build weather.js
    - name: ls -lrt if on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
            ls -lrt
    - name: dir if on windows
      if: matrix.os == 'windows-latest'
      run: |
            dir
